/*
 *  Licensed Materials - Property of IBM
 *  5725-I43 (C) Copyright IBM Corp. 2011, 2013. All Rights Reserved.
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

/************************************************************************
 * Implementation code for procedure - 'procedure1'
 *
 *
 * @return - invocationResult
 */
 
var SECTOR_KPI_Statement = WL.Server.createSQLStatement("SELECT SECTOR_NAME,PROCESS_REVIEW_GREEN_PERCENTAGE,PROCESS_REVIEW_GREEN_PERCENTAGE_PREV, PRODUCT_REVIEW_GREEN_PERCENTAGE,PRODUCT_REVIEW_GREEN_PERCENTAGE_PREV,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE_PREV,PM_MATCH_GAP_PERCENTAGE,PM_MATCH_GAP_PERCENTAGE_PREV, TROUBLED_PROJECTS_PERCENTAGE,TROUBLED_PROJECTS_PERCENTAGE_PREV,EW_PROJECTS_PERCENTAGE,EW_PROJECTS_PERCENTAGE_PREV,TROUBLED_GD_PERCENTAGE,TROUBLED_GD_PERCENTAGE_PREV,DIRECT_TROUBLED,DIRECT_TROUBLED_PREV,EARLY_WARNING_TO_TROUBLED,EARLY_WARNING_TO_TROUBLED_PREV,BAILED_OUT_FROM_TROUBLED,BAILED_OUT_FROM_TROUBLED_PREV,BAILED_OUT_FROM_EARLY_WARNING,BAILED_OUT_FROM_EARLY_WARNING_PREV,SEVEN_KEY_COMPLIANCE_PERCENTAGE,SEVEN_KEY_COMPLIANCE_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_RED_PERCENTAGE,SEVEN_KEY_HEALTH_RED_PERCENTAGE_PREV,IPWC_RISKS,IPWC_RISKS_PREV FROM DEAPP.SECTOR_KPI_METRICS_DATA");
function getSectorData() {
	return WL.Server.invokeSQLStatement({
		preparedStatement : SECTOR_KPI_Statement,
		parameters : []
	});
}

/************************************************************************
 * Implementation code for procedure - 'procedure2'
 *
 *
 * @return - invocationResult
 */
var KPI_METRICS_TARGET_Statement = WL.Server.createSQLStatement("SELECT PROCESS_REVIEW_GREEN, PRODUCT_REVIEW_GREEN, AI_CLOSURE_MET_SLA, PM_MATCH_GAP_COUNT,TROBULED_PROJECTS_COUNT, EW_PROJECTS_COUNT, TROBULED_GD_COUNT, DIRECT_TROUBLED,EARLY_WARNING_TO_TROUBLED, BAILED_OUT_FROM_TROUBLED, BAILED_OUT_FROM_EARLY_WARNING,SEVEN_KEY_COMPLIANCE, SEVEN_KEY_HEALTH_GREEN,SEVEN_KEY_HEALTH_AMBER,SEVEN_KEY_HEALTH_RED,IPWC_RISKS FROM DEAPP.KPI_METRICS_TARGETS"); 
function getMetricsTarget () {
	return WL.Server.invokeSQLStatement({
		preparedStatement : KPI_METRICS_TARGET_Statement,
		parameters : []
	});
}




var KPI_PAL_Statement = WL.Server.createSQLStatement("SELECT PAL_NAME,PROCESS_REVIEW_GREEN_PERCENTAGE,PROCESS_REVIEW_GREEN_PERCENTAGE_PREV, PRODUCT_REVIEW_GREEN_PERCENTAGE,PRODUCT_REVIEW_GREEN_PERCENTAGE_PREV,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE_PREV,PM_MATCH_GAP_PERCENTAGE,PM_MATCH_GAP_PERCENTAGE_PREV, TROUBLED_PROJECTS_PERCENTAGE,TROUBLED_PROJECTS_PERCENTAGE_PREV,EW_PROJECTS_PERCENTAGE,EW_PROJECTS_PERCENTAGE_PREV,TROUBLED_GD_PERCENTAGE,TROUBLED_GD_PERCENTAGE_PREV,DIRECT_TROUBLED,DIRECT_TROUBLED_PREV,EARLY_WARNING_TO_TROUBLED,EARLY_WARNING_TO_TROUBLED_PREV,BAILED_OUT_FROM_TROUBLED,BAILED_OUT_FROM_TROUBLED_PREV,BAILED_OUT_FROM_EARLY_WARNING,BAILED_OUT_FROM_EARLY_WARNING_PREV,SEVEN_KEY_COMPLIANCE_PERCENTAGE,SEVEN_KEY_COMPLIANCE_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_RED_PERCENTAGE,SEVEN_KEY_HEALTH_RED_PERCENTAGE_PREV,IPWC_RISKS,IPWC_RISKS_PREV from DEAPP.PAL_KPI_METRICS_DATA where SECTOR_NAME = ?"); 
function getPAL (selectedsect) {
	return WL.Server.invokeSQLStatement({
		preparedStatement : KPI_PAL_Statement ,
		parameters : [selectedsect]
	});
}

var KPI_PM_Statement = WL.Server.createSQLStatement("SELECT PM_NAME,PROCESS_REVIEW_GREEN_PERCENTAGE,PROCESS_REVIEW_GREEN_PERCENTAGE_PREV, PRODUCT_REVIEW_GREEN_PERCENTAGE,PRODUCT_REVIEW_GREEN_PERCENTAGE_PREV,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE,SLA_MET_ON_AI_CLOUSRE_PERCENTAGE_PREV,PM_MATCH_GAP_PERCENTAGE,PM_MATCH_GAP_PERCENTAGE_PREV, TROUBLED_PROJECTS_PERCENTAGE,TROUBLED_PROJECTS_PERCENTAGE_PREV,EW_PROJECTS_PERCENTAGE,EW_PROJECTS_PERCENTAGE_PREV,TROUBLED_GD_PERCENTAGE,TROUBLED_GD_PERCENTAGE_PREV,DIRECT_TROUBLED,DIRECT_TROUBLED_PREV,EARLY_WARNING_TO_TROUBLED,EARLY_WARNING_TO_TROUBLED_PREV,BAILED_OUT_FROM_TROUBLED,BAILED_OUT_FROM_TROUBLED_PREV,BAILED_OUT_FROM_EARLY_WARNING,BAILED_OUT_FROM_EARLY_WARNING_PREV,SEVEN_KEY_COMPLIANCE_PERCENTAGE,SEVEN_KEY_COMPLIANCE_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE,SEVEN_KEY_HEALTH_GREEN_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE,SEVEN_KEY_HEALTH_AMBER_PERCENTAGE_PREV,SEVEN_KEY_HEALTH_RED_PERCENTAGE,SEVEN_KEY_HEALTH_RED_PERCENTAGE_PREV,IPWC_RISKS,IPWC_RISKS_PREV from DEAPP.PM_KPI_METRICS_DATA where PAL_NAME = ? ORDER BY PM_NAME ASC"); 
function getPM (selectedsect) {
	return WL.Server.invokeSQLStatement({
		preparedStatement : KPI_PM_Statement ,
		parameters : [selectedsect]
	});
}


var KpiRefreshStatement = WL.Server.createSQLStatement("select * from DEAPP.KPI_REFRESH_DATES where KPI_NAME != 'Actuate Age' AND KPI_NAME != 'Landscape' ORDER BY KPI_NAME ASC");
function getrefreshData() {
	return WL.Server.invokeSQLStatement({
		preparedStatement : KpiRefreshStatement,
		parameters : []
	});
}